const data = [
  {
    name: "UFSM",
    key: "UFSM",
    isChecked: false,
    total: 18,
    filled: 12,
    approved: 10,
    reproved: 1,
    dropouts: 1,
    unnocupied: 6,
    requests_total: 170,
    requests_approved: 120,
    requests_reproved_requisites: 30,
    requests_reproved_schedule: 11,
    requests_reproved_vacancy: 9,
    students_received: 43,
    students_shared: 32,
    disciplines: [
      {
        name: "engineering",
        value: 10,
      },
      {
        name: "biology",
        value: 20,
      },
      {
        name: "health",
        value: 11,
      },
    ],
  },
  {
    name: "ABC",
    key: "ABC",
    isChecked: false,
    total: 9,
    filled: 7,
    approved: 5,
    reproved: 1,
    dropouts: 1,
    unnocupied: 2,
    requests_total: 160,
    requests_approved: 110,
    requests_reproved_requisites: 11,
    requests_reproved_schedule: 30,
    requests_reproved_vacancy: 9,
    students_received: 32,
    students_shared: 43,
    disciplines: [
      {
        name: "engineering",
        value: 4,
      },
      {
        name: "biology",
        value: 5,
      },
      {
        name: "health",
        value: 11,
      },
    ],
  },
  {
    name: "DEF",
    key: "DEF",
    isChecked: false,
    total: 18,
    filled: 12,
    approved: 10,
    reproved: 1,
    dropouts: 1,
    unnocupied: 6,
    requests_total: 150,
    requests_approved: 100,
    requests_reproved_requisites: 30,
    requests_reproved_schedule: 11,
    requests_reproved_vacancy: 9,
    students_received: 43,
    students_shared: 32,
    disciplines: [
      {
        name: "engineering",
        value: 10,
      },
      {
        name: "biology",
        value: 20,
      },
      {
        name: "health",
        value: 11,
      },
    ],
  },
  {
    name: "GHI",
    key: "GHI",
    isChecked: false,
    total: 9,
    filled: 7,
    approved: 5,
    reproved: 1,
    dropouts: 1,
    unnocupied: 2,
    requests_total: 140,
    requests_approved: 90,
    requests_reproved_requisites: 11,
    requests_reproved_schedule: 30,
    requests_reproved_vacancy: 9,
    students_received: 32,
    students_shared: 43,
    disciplines: [
      {
        name: "engineering",
        value: 4,
      },
      {
        name: "biology",
        value: 5,
      },
      {
        name: "health",
        value: 11,
      },
    ],
  },
];

export default data;
